// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proje008.Models;

namespace Proje008.Migrations
{
    [DbContext(typeof(MojoDbContext))]
    [Migration("20210107194752_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Proje008.Models.Anasayfa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AnasayfaAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnasayfaAciklama2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnasayfaAciklama3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnasayfaAciklama4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnasayfaAciklama5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnasayfaBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnasayfaBaslik2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnasayfaBaslik3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnasayfaBaslik4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnasayfaBaslik5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeopleSaysAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeopleSaysBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimYolu")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResimYolu1")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResimYolu2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResimYolu3")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResimYolu4")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Anasayfas");
                });
#pragma warning restore 612, 618
        }
    }
}
